name: portfolio
description: "Personal portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  responsive_framework: ^1.4.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.2.5
  timezone: ^0.9.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne.ttf
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode.ttf
